#!/bin/bash

# Script to get Alfred/Spotlight working again...
# Must run as root user!
if [ "$(id -u)" != "0" ]; then
  exec sudo "$0" "$@"
fi

echo "Starting Script..."

answer='z'
sleep 1
clear

echo $'-- Welcome to the Spotlight Index Refresh Tool --\n'
echo $'This script will destroy ALL current indexes\nfor ALL current volumes.\n'
echo $'It will then rebuild the proper indexes...\n'
echo $'\t**************************************'
echo $'\tThis can take a while depending on the\n\tamount of files/folders in your volume\n\tand the relative size of your volume.\n\tDrive and processor speeds also affect\n\tthe time to complete'
echo $'\t**************************************\n'
echo -n $'Are you sure you want to continue?\nEnter  (Y)es, (N)o, or (H)elp for more information...'
read answer

if [ $answer = "y" ] || [ $answer = "n" ] || [ $answer = "h" ]; then

  case $answer in
    [yY]|[yY][eE][sS])
    clear
    echo $'\nStarting clean and rebuild process...\n'
    sleep 2

    # 1. turn indexing off
    echo $'\nRemoving all volumes from the current index field...\n'
    mdutil -a -i off
    sleep 2

    # 2. deactivate Spotlight services and the index
    echo $'\nStopping all Spotlight Services...\n'
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist
    sleep 2

    # 3. delete Spotlight folder
    echo $'\nDeleting current Spotlight indexes...\n'
    rm -rf /.Spotlight*
    sleep 2

    # 4. delete metadata file
    echo $'\nForcing all volumes to start clean for new index...\n'
    rm -rf /.metadata_never_index
    sleep 2

    # 5. reload Spotlight service
    echo $'\nRestarting Spotlight Services...\n'
    launchctl load -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist
    sleep 2

    # 6. turn indexing on
    echo $'\nAdding all volumes to the new indexing scope...\n'
    mdutil -a -i on
    sleep 2

    #if [ $? -eq 0 ]; then
      # Step 7
    #else
      # echo "Process failed! Check your drive permissions and/or try running this script as root user."
    #fi

    # 7. rebuild index
    echo $'\nStarting the index rebuild process now...Please be patient.\n'
    mdutil -E /

    sleep 5
    clear

    echo $'\t*****************************************'
    echo $'\tScript is now complete.\n\tHowever, indexing is still in progress...'
    echo $'\t*****************************************\n'
    echo $'Check progress by searching in Spotlight for something...\n'
    echo $'\tIn the results panel, you will see the\n\t\'Indexing\' progress bar for your volume.\n'
    echo $'\tOnce finished, your Spotlight/Alfred\n\tsearching should work as intended.\n'
    sleep 5 ;;
  esac

  case $answer in
    [nN]|[nN][oO])

    echo $'\nUser Prompted Exit.' ;;
  esac

  case $answer in
    [hH]|[hH][eE][lL][pP])

    echo $'\nMore Information...\n'
    sleep 1
    man mdutil
    if [ $? -eq 0 ]; then
      exit 0
    fi ;;
  esac

else
  echo $'\nSorry, the script did not recognize your input answer.\n'
fi

echo $'\nExiting Script...\n'
sleep 1

exit 0
